// <auto-generated />
using System;
using FShop6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FShop6.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250722030438_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.BienTheModels", b =>
                {
                    b.Property<int>("MaBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienThe"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiBienThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamMaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBienThe");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("BienTheModels");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangChuViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrangChuViewModelId");

                    b.ToTable("DanhMucModel");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucSanPhamViewModel", b =>
                {
                    b.Property<string>("TenDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TrangChuViewModelId")
                        .HasColumnType("int");

                    b.HasKey("TenDanhMuc");

                    b.HasIndex("TrangChuViewModelId");

                    b.ToTable("DanhMucSanPhamViewModel");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.SanPhamModel", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("DanhMucSanPhamViewModelTenDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhMucSP")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangChuViewModelId")
                        .HasColumnType("int");

                    b.Property<int?>("TrangChuViewModelId1")
                        .HasColumnType("int");

                    b.Property<int?>("TrangChuViewModelId2")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("DanhMucSanPhamViewModelTenDanhMuc");

                    b.HasIndex("TrangChuViewModelId");

                    b.HasIndex("TrangChuViewModelId1");

                    b.HasIndex("TrangChuViewModelId2");

                    b.ToTable("SanPhamModel");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.TinTucModel", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("HinhAnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangChuViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("TrangChuViewModelId");

                    b.ToTable("TinTucModel");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.TrangChuViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("trangChuViewModels");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.BienTheModels", b =>
                {
                    b.HasOne("FShop6.Areas.KhachHang.Models.SanPhamModel", "SanPham")
                        .WithMany("BienThes")
                        .HasForeignKey("SanPhamMaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucModel", b =>
                {
                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("DanhMucPhoBien")
                        .HasForeignKey("TrangChuViewModelId");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucSanPhamViewModel", b =>
                {
                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("DanhMucSanPhamHienThi")
                        .HasForeignKey("TrangChuViewModelId");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.SanPhamModel", b =>
                {
                    b.HasOne("FShop6.Areas.KhachHang.Models.DanhMucModel", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FShop6.Areas.KhachHang.Models.DanhMucSanPhamViewModel", null)
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucSanPhamViewModelTenDanhMuc");

                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("SanPhamMoi")
                        .HasForeignKey("TrangChuViewModelId");

                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("SanPhamNoiBat")
                        .HasForeignKey("TrangChuViewModelId1");

                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("SanPhamPhoBien")
                        .HasForeignKey("TrangChuViewModelId2");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.TinTucModel", b =>
                {
                    b.HasOne("FShop6.Areas.KhachHang.Models.TrangChuViewModel", null)
                        .WithMany("TinTuc")
                        .HasForeignKey("TrangChuViewModelId");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucModel", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.DanhMucSanPhamViewModel", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.SanPhamModel", b =>
                {
                    b.Navigation("BienThes");
                });

            modelBuilder.Entity("FShop6.Areas.KhachHang.Models.TrangChuViewModel", b =>
                {
                    b.Navigation("DanhMucPhoBien");

                    b.Navigation("DanhMucSanPhamHienThi");

                    b.Navigation("SanPhamMoi");

                    b.Navigation("SanPhamNoiBat");

                    b.Navigation("SanPhamPhoBien");

                    b.Navigation("TinTuc");
                });
#pragma warning restore 612, 618
        }
    }
}
