<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\TrangChu\" />
    <Folder Include="Areas\Admin\Views\CaiDat\" />
    <Folder Include="Areas\Admin\Views\TinTuc\" />
    <Folder Include="Areas\Admin\Views\ThongKe\" />
    <Folder Include="Areas\Admin\Views\QuanLyDonHang\" />
    <Folder Include="Areas\Admin\Views\QuanLyDanhMuc\" />
    <Folder Include="Areas\Admin\Views\QuanLyKhachHang\" />
    <Folder Include="Areas\Admin\Views\QuanLyTaiKhoan\" />
    <Folder Include="Areas\Admin\Views\QuanLySanPham\" />
    <Folder Include="Areas\Admin\Views\TaiKhoan\" />
    <Folder Include="Areas\Admin\Views\Shared\" />
    <Folder Include="Areas\KhachHang\Models\" />
    <Folder Include="Data\" />
    <Folder Include="CauHinh\" />
    <Folder Include="TienIch\" />
    <Folder Include="Services\" />
    <Folder Include="wwwroot\Admin\css\" />
    <Folder Include="wwwroot\Admin\js\" />
    <Folder Include="wwwroot\Admin\images\" />
    <Folder Include="wwwroot\KhachHang\images\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
